import type { Metadata } from "next";
import { DotGothic16, Noto_Sans_JP } from "next/font/google";
import "./globals.css";

const dotGothic16 = DotGothic16({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-heading",
});

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${dotGothic16.variable} ${notoSansJP.variable}`}>
      <body className="antialiased font-body">
        {children}
      </body>
    </html>
  );
}
